apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-sonarqube
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/tools/sonarqube
    repoURL: https://github.com/seansund/gittest-repo.git
    targetRevision: main
    helm:
      releaseName: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
