apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-pact-broker
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/tools/pact-broker
    repoURL: https://github.com/seansund/gittest-repo.git
    targetRevision: main
    helm:
      releaseName: pact-broker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
