apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace-tools.yaml
  - base/tools-artifactory-artifactory-sa.yaml
  - base/tools-artifactory-artifactory-scc.yaml
  - base/tools-sonarqube-sonarqube-rbac.yaml
  - base/tools-sonarqube-sonarqube-sa.yaml
  - base/tools-sonarqube-sonarqube-scc.yaml
  - base/tools-tools-group.yaml
