apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-artifactory-artifactory-sa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/tools/artifactory-artifactory-sa
    repoURL: https://github.com/seansund/gittest-repo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
        - /secrets
      kind: ServiceAccount
