apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: artifactory-config
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
rules:
- "apiGroups":
  - ""
  "resourceNames": null
  "resources":
  - "secrets"
  - "configmaps"
  "verbs":
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: artifactory-config
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: artifactory-config
subjects:
- kind: ServiceAccount
  name: artifactory-config
  namespace: tools
---
